const $ = (s) => document.querySelector(s);
const api = async (url, options) => { const r = await fetch(url, options); const d = await r.json(); if (!r.ok) throw new Error(d.error || d.message || 'Request failed'); return d; };
const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const average = (values) => values.length ? values.reduce((a,b)=>a+b,0) / values.length : 0;
const chatHistory = [];
async function loadDashboard() {
  const [overview, sentiment, topics, entities, audience] = await Promise.all([api('/api/overview'),api('/api/sentiment'),api('/api/topics'),api('/api/entities'),api('/api/audience')]);
  const scored=sentiment.points.filter(p=>Number.isFinite(p.score)&&!['unavailable','skipped_empty'].includes(p.source)&&p.label!=='unavailable');
  $('#totalPosts').textContent=overview.total_posts; $('#avgSentiment').textContent=scored.length?average(scored.map(p=>p.score)).toFixed(2):'—'; $('#topicCount').textContent=topics.topics.filter(t=>t.source==='BERTopic').length;
  const storage=overview.ingest?.storage;
  $('#savedCount').textContent=storage?.verified_rows??'—';
  $('#storageStatus').textContent=storage?.verified_rows===overview.total_posts&&overview.total_posts?'NLP rows verified · metadata '+(storage.metadata_written?'saved':'pending'):storage?.errors?.[0]||'Waiting for verification';
  const isLive=overview.source==='live'; $('#sourceLabel').textContent=isLive?'Live public data':overview.source==='seeded'?'Seeded fallback':'No data yet'; $('#sourceDot').style.background=isLive?'var(--teal)':'var(--yellow)'; $('#engagement').textContent=(overview.engagement || 0).toLocaleString(); $('#ingestStatus').textContent=overview.ingest?.message || 'Ready';
  renderBars(sentiment.points); renderTopics(topics.topics); renderEntities(entities.entities); renderAudience(audience.segments); renderEvidence(topics.topics.flatMap((t)=>t.evidence).slice(0,5)); renderInsights(overview,sentiment.points,topics.topics,entities.entities,audience.segments);
}
function ensureInsights(){if($('#insights'))return;document.querySelector('.composer').insertAdjacentHTML('beforebegin',`<section id="insights" class="insights-grid"><article class="panel"><div class="panel-head"><div><span class="eyebrow">SENTIMENT ANALYSIS</span><h3>Writer mood distribution</h3></div></div><div id="sentimentDistribution" class="analysis-bars"></div></article><article class="panel"><div class="panel-head"><div><span class="eyebrow">EVENT ANALYSIS</span><h3>Incident severity</h3></div><span class="muted">Separate from mood</span></div><div id="severityDistribution" class="analysis-bars"></div></article><article class="panel"><div class="panel-head"><div><span class="eyebrow">AUDIENCE SIGNALS</span><h3>Aggregate demographics</h3></div></div><div id="demographicDistribution" class="analysis-bars"></div><p class="footnote">Only detected language and permitted public signals. No age, gender, caste, religion, ethnicity or other protected traits are inferred.</p></article><article class="panel"><div class="panel-head"><div><span class="eyebrow">ENTITY ANALYSIS</span><h3>Locations and organisations</h3></div></div><div id="entityDistribution" class="analysis-bars"></div></article></section>`)}
function analysisBars(items,total,format=(x)=>x){const max=Math.max(...items.map(x=>x.value),1);return items.map(x=>`<div class="analysis-row"><div class="analysis-label"><span>${esc(x.label)}</span><strong>${format(x.value)}</strong></div><div class="analysis-track"><span style="width:${Math.max(3,x.value/max*100)}%"></span></div><small class="muted">${total?Math.round(x.value/total*100):0}%</small></div>`).join('')||'<p class="muted">No analysed records yet.</p>'}
function renderInsights(overview,points,topics,entities,audience){ensureInsights();const total=points.length;const sentiment=['positive','neutral','negative','unavailable'].map(label=>({label,value:points.filter(p=>p.label===label).length})).filter(x=>x.value);$('#sentimentDistribution').innerHTML=analysisBars(sentiment,total);const severity=Object.entries(overview.event_severity||{}).map(([label,value])=>({label:`Severity ${label}`,value:Number(value)}));$('#severityDistribution').innerHTML=analysisBars(severity,total);const demo=audience.slice(0,6).map(x=>({label:x.name,value:x.count}));$('#demographicDistribution').innerHTML=analysisBars(demo,total);const ents=entities.slice(0,6).map(x=>({label:`${x.text} · ${x.label}`,value:x.count}));$('#entityDistribution').innerHTML=analysisBars(ents,total)}
function renderBars(points){const max=Math.max(...points.map((p)=>Math.abs(p.score || 0)),.2);$('#sentimentBars').innerHTML=points.map((p)=>`<div class="bar-wrap"><div class="bar ${(p.score||0)>=0?'pos':'neg'}" style="height:${Math.max(5,Math.abs(p.score||0)/max*100)}%" title="${esc(p.label)} ${p.score}"></div><span class="bar-label">${new Date(p.date).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></div>`).join('') || '<p class="muted">Run ingestion to see the RoBERTa trend.</p>'}
function renderTopics(topics){const max=Math.max(...topics.map((t)=>t.posts),1);$('#topics').innerHTML=topics.map((t)=>`<div class="topic-row"><div style="flex:1"><div class="topic-name"><i class="topic-dot"></i>${esc(t.topic)}</div><div class="meter"><span style="width:${t.posts/max*100}%"></span></div><small class="muted">${esc(t.source || 'pending')}</small></div><span class="topic-score">${t.posts}</span></div>`).join('') || '<p class="muted">BERTopic runs after live comments are analysed.</p>'}
function renderEntities(entities){$('#entities').innerHTML=entities.slice(0,7).map((e)=>`<div class="entity-row"><span>${esc(e.text)} <small class="muted">${esc(e.label)}</small></span><span class="entity-count">${e.count}</span></div>`).join('') || '<p class="muted">No entities yet.</p>'}
function renderAudience(segments){$('#audience').innerHTML=segments.slice(0,6).map((s)=>`<div class="audience-row"><span>${esc(s.name)}</span><span class="audience-count">${s.count}</span></div>`).join('') || '<p class="muted">No audience signals yet.</p>'}
function renderEvidence(urls){$('#evidence').innerHTML=[...new Set(urls)].map((url)=>`<div class="evidence-row"><a href="${esc(url)}" target="_blank" rel="noreferrer">${esc(url)}</a><span>source</span></div>`).join('') || '<p class="muted">Evidence links appear after live ingestion.</p>'}
function addBubble(role,content,meta=''){const node=document.createElement('div');node.className=`bubble ${role}`;node.innerHTML=`<div>${esc(content).replace(/\n/g,'<br>')}</div>${meta?`<small class="bubble-meta">${esc(meta)}</small>`:''}`;$('#chatLog').appendChild(node);$('#chatLog').scrollTop=$('#chatLog').scrollHeight;return node;}
function setChatBusy(busy){$('#chatSend').disabled=busy;$('#chatInput').disabled=busy;$('#chatSend').textContent=busy?'…':'Send';}
$('#refreshBtn').addEventListener('click',async()=>{const b=$('#refreshBtn');b.textContent='Starting…';try{await api('/api/ingest/run',{method:'POST'});await waitForIngest();await loadDashboard();}catch(e){$('#ingestStatus').textContent=e.message;}finally{b.textContent='Run ingestion'}});
async function waitForIngest(){for(let i=0;i<60;i++){const s=await api('/api/ingest/status');if(!s.running)return s;await new Promise(r=>setTimeout(r,1000));}return null;}
$('#chatToggle').addEventListener('click',()=>{ $('#chatPanel').classList.add('open'); $('#chatInput').focus(); }); $('#chatClose').addEventListener('click',()=>$('#chatPanel').classList.remove('open'));
document.querySelectorAll('.suggestions button').forEach((b)=>b.addEventListener('click',()=>{$('#chatInput').value=b.textContent;$('#chatForm').requestSubmit()}));
$('#chatForm').addEventListener('submit',async(e)=>{e.preventDefault();const input=$('#chatInput'),q=input.value.trim();if(!q||$('#chatSend').disabled)return;addBubble('user',q);input.value='';setChatBusy(true);const thinking=addBubble('bot','Thinking…','MiniMax is checking the corpus and conversation context.');try{const r=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,history:chatHistory})});thinking.remove();addBubble('bot',r.answer,`${r.scope || 'answer'} · ${r.retrieval || 'corpus retrieval'}${r.evidence?.length?` · ${r.evidence.length} evidence link(s)`:''}`);chatHistory.push({role:'user',content:q},{role:'assistant',content:r.answer});}catch(err){thinking.remove();addBubble('bot',err.message,'Please retry or check the service status.');}finally{setChatBusy(false);input.focus();}});
$('#chatInput').addEventListener('keydown',(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm').requestSubmit();}});
$('#checkDraft').addEventListener('click',async()=>{const text=$('#draftText').value;if(!text.trim())return;const b=$('#checkDraft');b.disabled=true;b.textContent='Checking…';try{const result=await api('/api/plugin/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});$('#pluginStatus').textContent=`Stored ${result.verdict} decision via ${result.storage || result.provider}`;$('#pluginResult').innerHTML=`<strong>${esc(result.verdict)}</strong><br>${esc(result.corrected_text || result.reason || 'No change suggested.')}${result.issues?.length?`<br><small>${result.issues.map((i)=>esc(i.message)).join(' ')}</small>`:''}`;}catch(e){$('#pluginStatus').textContent=e.message;}finally{b.disabled=false;b.textContent='Check wording';}});
let dashboardLoading=false;
async function refreshDashboard(){if(dashboardLoading)return;dashboardLoading=true;try{await loadDashboard();}catch(e){$('#sourceLabel').textContent=e.message;$('#ingestStatus').textContent='Service unavailable';}finally{dashboardLoading=false;}}
refreshDashboard();
setInterval(()=>{if(!document.hidden)refreshDashboard();},4000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshDashboard();});
