create extension if not exists vector;
create table if not exists raw_posts (id text primary key, source text not null default 'x', text text not null, created_at timestamptz not null, source_url text not null, lang text, location text, metrics jsonb not null default '{}'::jsonb, pii_redacted boolean not null default true, inserted_at timestamptz not null default now());
create table if not exists posts_nlp (id text primary key references raw_posts(id) on delete cascade, content_hash text not null, sentiment_label text not null, sentiment_score double precision not null, sentiment_confidence double precision, sentiment_source text not null, event_polarity jsonb not null default '{}'::jsonb, entities jsonb not null default '[]'::jsonb, language text, topic text, processed_at timestamptz not null default now());
create table if not exists post_embeddings (post_id text primary key references raw_posts(id) on delete cascade, model_name text not null, embedding vector(384), content_hash text not null, created_at timestamptz not null default now());
create table if not exists topics (topic_id text primary key, label text not null, window_start timestamptz, window_end timestamptz, volume integer not null default 0, sentiment_mean double precision);
create table if not exists topic_posts (topic_id text references topics(topic_id) on delete cascade, post_id text references raw_posts(id) on delete cascade, probability double precision, primary key (topic_id, post_id));
create table if not exists audience_segments (segment_key text primary key, label text not null, basis text not null, volume integer not null default 0, confidence double precision, window_start timestamptz, window_end timestamptz);
create table if not exists chat_evidence (id bigserial primary key, question text not null, answer text not null, evidence_urls jsonb not null default '[]'::jsonb, created_at timestamptz not null default now());
create table if not exists moderation_logs (id uuid primary key default gen_random_uuid(), original_text text not null, corrected_text text, issues jsonb not null default '[]'::jsonb, verdict text not null, provider text not null, created_at timestamptz not null default now());
